from __future__ import annotations

import math
from datetime import date

import numpy as np
import svgwrite

from vectorizer.config import VectorizerConfig
from vectorizer.types import Primitive, PrimitivesResult, SVGResult

from .layers import style_for


def _fmt(value: float, decimals: int) -> str:
    return f"{value:.{decimals}f}"


def _arc_path(center: tuple[float, float], radius: float,
               start_deg: float, end_deg: float, decimals: int) -> str:
    """Build SVG path 'd' string for a circular arc (col/row → x/y)."""
    cr, cc = center
    start_rad = math.radians(start_deg)
    end_rad   = math.radians(end_deg)

    # SVG x = col, y = row
    sx = cc + radius * math.cos(start_rad)
    sy = cr + radius * math.sin(start_rad)
    ex = cc + radius * math.cos(end_rad)
    ey = cr + radius * math.sin(end_rad)

    span = (end_deg - start_deg) % 360
    large_arc = 1 if span > 180 else 0

    f = lambda v: _fmt(v, decimals)
    return (
        f"M {f(sx)},{f(sy)} "
        f"A {f(radius)},{f(radius)} 0 {large_arc},1 {f(ex)},{f(ey)}"
    )


def build_svg(prims_result: PrimitivesResult, config: VectorizerConfig,
              image_shape: tuple[int, int] | None = None) -> SVGResult:
    """Assemble all primitives into an SVG document."""
    d = config.svg_decimal_places
    primitives = prims_result.primitives

    if not primitives and image_shape is not None:
        h, w = image_shape
        vb = (0.0, 0.0, float(w), float(h))
    elif not primitives:
        vb = (0.0, 0.0, 100.0, 100.0)
    else:
        all_pts = []
        for p in primitives:
            if p.points is not None and len(p.points):
                all_pts.append(p.points)
            if p.center is not None:
                cr, cc = p.center
                r = p.radius or 0
                all_pts.append(np.array([[cr - r, cc - r], [cr + r, cc + r]], dtype=np.float32))
        if all_pts:
            pts = np.vstack(all_pts)
            # col→x, row→y
            min_x, min_y = float(pts[:, 1].min()), float(pts[:, 0].min())
            max_x, max_y = float(pts[:, 1].max()), float(pts[:, 0].max())
        else:
            min_x = min_y = 0.0
            max_x = max_y = 100.0
        pad = 5.0
        vb = (min_x - pad, min_y - pad, max_x - min_x + 2 * pad, max_y - min_y + 2 * pad)

    vb_str = f"{_fmt(vb[0],d)} {_fmt(vb[1],d)} {_fmt(vb[2],d)} {_fmt(vb[3],d)}"
    dwg = svgwrite.Drawing(size=("100%", "100%"), viewBox=vb_str)

    # Metadata
    dwg.set_desc(
        title="Vectorized architectural drawing",
        desc=(
            f"Generated by vectorizer v0.1.0 on {date.today().isoformat()}. "
            f"DPI: {config.output_dpi}."
        ),
    )

    # Group primitives by layer
    from collections import defaultdict
    by_layer: dict[str, list[Primitive]] = defaultdict(list)
    for p in primitives:
        by_layer[p.layer].append(p)

    for layer_id, layer_prims in by_layer.items():
        style = style_for(layer_id)
        grp = dwg.g(
            id=f"layer-{layer_id}",
            stroke=style['stroke'],
            stroke_width=str(style['stroke_width']),
            fill=style['fill'],
        )

        for prim in layer_prims:
            el = _primitive_to_element(prim, dwg, d)
            if el is not None:
                grp.add(el)

        dwg.add(grp)

    return SVGResult(svg_string=dwg.tostring(), viewbox=vb)


def _primitive_to_element(prim: Primitive, dwg: svgwrite.Drawing, decimals: int):
    f = lambda v: round(float(v), decimals)

    if prim.kind == 'line' and len(prim.points) >= 2:
        r0, c0 = prim.points[0]
        r1, c1 = prim.points[1]
        return dwg.line(start=(f(c0), f(r0)), end=(f(c1), f(r1)))

    if prim.kind == 'circle' and prim.center is not None and prim.radius is not None:
        cr, cc = prim.center
        return dwg.circle(center=(f(cc), f(cr)), r=f(prim.radius))

    if prim.kind == 'arc' and prim.center is not None:
        d_str = _arc_path(prim.center, prim.radius, prim.start_angle, prim.end_angle, decimals)
        return dwg.path(d=d_str, fill='none')

    if prim.kind == 'polyline' and len(prim.points) >= 2:
        pts = [(f(c), f(r)) for r, c in prim.points]
        return dwg.polyline(points=pts)

    return None
